---
title: "AI in RStudio"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: Description about Course/Book.
favicon: assets/AnVIL_style/anvil_favicon.ico
---


# About this Book {-}

This book is part of a series of books for the Genomic Data Science Analysis, Visualization, and Informatics Lab-space (AnVIL) of the National Human Genome Research Institute (NHGRI). Learn more about AnVIL by visiting https://anvilproject.org or reading the [article in Cell Genomics](https://www.sciencedirect.com/science/article/pii/S2666979X21001063).

## Skills Level {-} 

::: {.notice}
_Genetics_
<!-- **Novice**: no genetics knowledge needed -->

_Programming skills_
<!-- **Novice**: no programming experience needed -->
:::

## AnVIL Collection {-}

Please check out our full collection of AnVIL and related resources: https://hutchdatascience.org/AnVIL_Collection/

# Learning Objectives {-}

1. Provision GPU-accelerated cloud infrastructure deploy local AI models in RStudio on AnVIL.
1. Leverage `gander` AI assistant in RStudio for context-aware data exploration and coding.
1. Use AI prompts in `gander` to drive RNA-seq data exploration and analysis with tidyverse and DESeq2.

# Table of Contents {-}

1. About this Course

	> Welcome	
	>	
	> Learning Goals
	>
	> Abstract
	>
	> Introduction
	>
	> Ethical use of AI for data analysis
	>	
	> Methods
	>
	> Quiz

2. Run Local Models
    
	> Learning objectives
	>
    > RStudio Setup with GPU on AnVIL
	>
    > Install Ollama server and download qwen3-coder
	>
    > Connect R to the local AI server via ellmer
	>
    > Chapter Quiz

3. Explore data with gander

    > Learning objectives
	>
    > Configure gander and setup keyboard shortcut
	>
    > Good habits: using gander_peek() and requesting code explanations
	>
    > Import the data from Google Cloud Storage 
	>
    > Explore RNA-seq counts and metadata with gander and Tidyverse
	>
    > Chapter Quiz

4. Run DESeq2 
    > Learning objectives
	>
    > Filter low counts
	>
    > Run differential expression with DESeq2
	>
    > Visualize plots and save results
	>
    > Chapter Quiz

5. API Hosts 

6. Troubleshooting and Tips
